"""Domain constants and enumerations used across the system."""

ROLES = ["ADMIN", "RELIEF_CENTER_OPERATOR", "VOLUNTEER_LOGISTICS"]
USER_STATUSES = ["ACTIVE", "INACTIVE"]

EMERGENCY_TYPES = [
    "FLOOD", "EARTHQUAKE", "CYCLONE", "LANDSLIDE",
    "DROUGHT", "FIRE", "EPIDEMIC", "OTHER",
]
SEVERITIES = ["LOW", "MEDIUM", "HIGH", "CRITICAL"]
EMERGENCY_STATUSES = ["ACTIVE", "MONITORING", "COMPLETED"]

URGENCIES = ["LOW", "MEDIUM", "HIGH", "CRITICAL"]
REQUEST_STATUSES = [
    "PENDING", "APPROVED", "REJECTED", "PARTIALLY_ALLOCATED",
    "ALLOCATED", "WAITING_FOR_STOCK", "IN_DELIVERY", "COMPLETED",
]

RESOURCE_CATEGORIES = [
    "FOOD", "WATER", "MEDICINE", "BLANKETS", "HYGIENE_KITS",
    "BABY_SUPPLIES", "CLOTHING", "FIRST_AID_KITS", "OTHER",
]

TRANSACTION_TYPES = [
    "IN", "OUT", "ADJUST", "RESERVE", "RELEASE",
    "TRANSFER_IN", "TRANSFER_OUT", "EXPIRED_WRITE_OFF",
]

CENTER_STATUSES = ["ACTIVE", "FULL", "INACTIVE"]
ALLOCATION_STATUSES = ["RESERVED", "DISPATCHED", "COMPLETED", "CANCELLED"]
DELIVERY_STATUSES = [
    "PREPARING", "DISPATCHED", "IN_TRANSIT", "DELIVERED", "FAILED", "CANCELLED",
]
NOTIFICATION_TYPES = ["CRITICAL", "WARNING", "INFO"]

PRIORITY_LEVELS = {"LOW": (0, 30), "MEDIUM": (31, 60), "HIGH": (61, 80), "CRITICAL": (81, 100)}

PRIORITY_WEIGHTS = {
    "severity": 0.30,
    "population": 0.25,
    "shortage": 0.20,
    "urgency": 0.15,
    "time_criticality": 0.10,
}

DELIVERY_TRANSITIONS = {
    "PREPARING": {"DISPATCHED", "CANCELLED"},
    "DISPATCHED": {"IN_TRANSIT", "FAILED", "CANCELLED"},
    "IN_TRANSIT": {"DELIVERED", "FAILED"},
    "DELIVERED": set(),
    "FAILED": set(),
    "CANCELLED": set(),
}

PER_CAPITA_DAILY_CONSUMPTION = {
    "FOOD": 0.6,
    "WATER": 3.0,
    "MEDICINE": 0.01,
    "BLANKETS": 0.02,
    "HYGIENE_KITS": 0.01,
    "BABY_SUPPLIES": 0.005,
    "CLOTHING": 0.01,
    "FIRST_AID_KITS": 0.004,
    "OTHER": 0.01,
}

SEVERITY_MULTIPLIER = {"LOW": 1.0, "MEDIUM": 1.15, "HIGH": 1.35, "CRITICAL": 1.6}
